# fly.toml app configuration file generated for mdl on 2023-06-08T07:30:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mdl"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
